namespace:
  name: sandbox

replicaCount: 1

image:
  repository: asheshanr/techtrends
  pullPolicy: IfNotPresent
  tag: latest

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  
service:
  type: ClusterIP
  port: 4111
  targetPort: 3111
  containerPort: 3111
  protocol: TCP

livenessProbe:
  httpGet:
    path: /healthz
    port: 3111
readinessProbe:
  httpGet:
    path: /healthz
    port: 3111
resources:
  requests:
    memory: 64Mi
    cpu: 250m
  limits:
    memory: 128Mi
    cpu: 500m
serviceAccount:
  create: false

nodeSelector: {}

tolerations: []

affinity: {}
